### CONFIG
SCREEN_SIZE = (720, 576)
### PHYSICS CONFIG
COLLTYPE_DEFAULT = 0
COLLTYPE_MOUSE = 1
COLLTYPE_BALL = 2
COLLTYPE_ZEYTIN = 3
COLLTYPE_LAHMACUN = 4
COLLTYPE_MAGNOLYA = 5
COLLTYPE_MUCVER = 6
COLLTYPE_KABAK = 7
COLLTYPE_HANIMGOBEGI = 8
COLLTYPE_ISPANAK = 9
COLLTYPE_DEADZONE = 10

X, Y = 0, 1